# This file was generated by GoReleaser. DO NOT EDIT.
cask "compair" do
  name "compair"
  desc "Cross-repo review from the terminal"
  homepage "https://compair.sh"
  version "0.3.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "compair"

  on_macos do
    on_intel do
      url "https://github.com/RocketResearch-Inc/compair-cli/releases/download/v#{version}/compair_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/RocketResearch-Inc/compair-cli/"
      sha256 "793af22922a08eecd1e154ab92e09fca5ab1faa31f8fc7124253230852d38aea"
    end
    on_arm do
      url "https://github.com/RocketResearch-Inc/compair-cli/releases/download/v#{version}/compair_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/RocketResearch-Inc/compair-cli/"
      sha256 "ab81729337d0e328e9a01a25473a2463fc739661ccc1ef8dbef85e9c5e639a40"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/compair"]
    end
  end

  caveats do
    "Run `compair demo` for the fastest first run."
  end

  # No zap stanza required
end
