# This file was generated by GoReleaser. DO NOT EDIT.
cask "compair" do
  version "0.3.10"

  on_macos do
    on_intel do
      url "https://github.com/RocketResearch-Inc/compair-cli/releases/download/v#{version}/compair_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/RocketResearch-Inc/compair-cli/"
      sha256 "ff96172e7b1ed5f96f4bd6e5c2c4c33861996fecd5ced7a1c968c96b4d3858d6"
    end
    on_arm do
      url "https://github.com/RocketResearch-Inc/compair-cli/releases/download/v#{version}/compair_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/RocketResearch-Inc/compair-cli/"
      sha256 "e2e043a0a7e46ad0a7bf67833a8befa449047fee5817eed1c6e8947bb807404c"
    end
  end

  name "compair"
  desc "Cross-repo review from the terminal"
  homepage "https://compair.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "compair"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/compair"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `compair demo` for the fastest first run.
  EOS
end
