# This file was generated by GoReleaser. DO NOT EDIT.
cask "compair" do
  version "0.3.12"

  on_macos do
    on_intel do
      url "https://github.com/RocketResearch-Inc/compair-cli/releases/download/v#{version}/compair_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/RocketResearch-Inc/compair-cli/"
      sha256 "7978b569baa3a0df9d5a6e77a4bbe61dabbaaa694057ff6137cde83277c4aac6"
    end
    on_arm do
      url "https://github.com/RocketResearch-Inc/compair-cli/releases/download/v#{version}/compair_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/RocketResearch-Inc/compair-cli/"
      sha256 "0ce844c20956ba0dede29bb1d43bd8b6f5f2b0fb7c5038b8342797e400bf6499"
    end
  end

  name "compair"
  desc "Cross-repo review from the terminal"
  homepage "https://compair.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "compair"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/compair"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `compair demo` for the fastest first run.
  EOS
end
